#!/bin/bash

#git branch -d upm &> /dev/null || echo upm branch not found
#git subtree split -P "Packages/com.sark.tiled_camera" -b upm
#git checkout upm

if git cat-file -e "master:Documentation~"; then
  git checkout master Documentation~
  git config --global user.name 'github-bot'
  git config --global user.email 'github-bot@users.noreply.github.com'
  git commit -am "fix: Copy readme to package root."
fi


#git push -f -u origin upmgit 